# -*- coding: utf-8 -*-
"""RedesPeso/Dirigidas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lxn0-PFXBY7pkGGHlm2KgmlEERCjcCTG
"""

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from google.colab import files
import pandas as pd

uploaded = files.upload()

paises= files.upload()

datos = pd.read_csv('comtrade_trade_data_total_2003.csv', header=0, usecols = ['Reporter Code','Trade Flow Code','Partner Code','Value'])

paises = pd.read_csv('Country Code and Name ISO2 ISO3.csv')



excluir = [472,899,471,129,221,97,697,492,838,473,536,637,290,527,577,490,568,636,839,879,0]

condicion = (datos['Reporter Code'].isin(excluir))| (datos['Partner Code'].isin(excluir))|(datos['Reporter Code'] == datos['Partner Code'])
datos = datos[~condicion]

datos

exportaciones=datos[datos['Trade Flow Code']==2]



importaciones=datos[datos['Trade Flow Code']==1]



enlaces_in=importaciones.groupby(['Reporter Code','Partner Code'])['Value'].sum().reset_index()

enlaces_out=exportaciones.groupby(['Reporter Code','Partner Code'])['Value'].sum().reset_index()

enlaces_in.columns = ['origen','destino','valor']
enlaces_in

enlaces_out.columns = ['origen','destino','valor']
enlaces_out

enlaces = enlaces_out.append(enlaces_in,ignore_index = True,sort = False)

enlaces

enlaces_sim=enlaces.groupby(['origen','destino'])['valor'].mean().reset_index()

enlaces_sim

DG = nx.DiGraph()

edges = zip(enlaces_sim.origen.values, enlaces_sim.destino.values,enlaces_sim.valor.values)

DG.add_weighted_edges_from(edges)

nx.draw(DG)

nodos = list(DG.nodes())
nx.draw(DG.subgraph(nodos[:10]))

grados_in=list(dict(DG.in_degree).values())

grados_out=list(dict(DG.out_degree).values())

plt.plot(grados_in,grados_out,'o')

digri = list(dict(DG.degree).values())
mean_deg = []
for j in DG.nodes():
  vecinos = list(DG[j])
  degs = []
  for i in vecinos:
    degs.append(DG.degree[i])
  mean_deg.append(np.mean(degs))

